export const usernameList = ['Dave', 'Sarah', 'Joe'];
export const emailList = [
	'dave@example.com',
	'sarah@example.com',
	'joe@example.com',
];
export const users = [
	{
		email: 'dave@example.com',
		username: 'Dave',
		password: 'password',
		theme: 'light',
		currentId: 4,
		logs: [
			{
				sessionId: 1,
				sessionName: 'Session 1 - Dave',
				sessionDate: '2022-06-16',
				startLoc: 'Town',
				endLoc: 'Cave',
				sessionNotes: 'Stuff happened',
			},
			{
				sessionId: 2,
				sessionName: 'Session 2 - Dave',
				sessionDate: '2022-06-23',
				startLoc: 'Cave',
				endLoc: 'Dungeon',
				sessionNotes: 'More stuff happened',
			},
			{
				sessionId: 3,
				sessionName: 'Session 3 - Dave',
				sessionDate: '2022-06-30',
				startLoc: 'Dungeon',
				endLoc: 'Town',
				sessionNotes: 'Even more stuff happened',
			},
		],
	},
	{
		email: 'sarah@example.com',
		username: 'Sarah',
		password: 'password',
		theme: 'light',
		currentId: 4,
		logs: [
			{
				sessionId: 1,
				sessionName: 'Session 1 - Sarah',
				sessionDate: '2022-06-16',
				startLoc: 'Town',
				endLoc: 'Cave',
				sessionNotes: 'Stuff happened',
			},
			{
				sessionId: 2,
				sessionName: 'Session 2 - Sarah',
				sessionDate: '2022-06-23',
				startLoc: 'Cave',
				endLoc: 'Dungeon',
				sessionNotes: 'More stuff happened',
			},
			{
				sessionId: 3,
				sessionName: 'Session 3 - Sarah',
				sessionDate: '2022-06-30',
				startLoc: 'Dungeon',
				endLoc: 'Town',
				sessionNotes: 'Even more stuff happened',
			},
		],
	},
	{
		email: 'joe@example.com',
		username: 'Joes',
		password: 'password',
		theme: 'dark',
		currentId: 4,
		logs: [
			{
				sessionId: 1,
				sessionName: 'Session 1 - Joe',
				sessionDate: '2022-06-16',
				startLoc: 'Town',
				endLoc: 'Cave',
				sessionNotes: 'Stuff happened',
			},
			{
				sessionId: 2,
				sessionName: 'Session 2 - Joe',
				sessionDate: '2022-06-23',
				startLoc: 'Cave',
				endLoc: 'Dungeon',
				sessionNotes: 'More stuff happened',
			},
			{
				sessionId: 3,
				sessionName: 'Session 3 - Joe',
				sessionDate: '2022-06-30',
				startLoc: 'Dungeon',
				endLoc: 'Town',
				sessionNotes: 'Even more stuff happened',
			},
		],
	},
];
